name = "dployr-web"
compatibility_date = "2024-12-30"
pages_build_output_dir = "./dist"

[assets]
directory = "public"

[env.production.vars]
VITE_APP_VERSION = ""
VITE_BASE_URL = "https://base.dployr.io"
